-- ============================================================================
-- SMART PEN ACADEMY - MIGRATION 008: FEE RECEIPT STANDARDIZATION & IMMUTABILITY
-- 008_standardize_fee_receipt_numbers.sql
--
-- 1. Create atomic per-student daily sequence table: receipt_counters
-- 2. Create trigger function to generate immutable receipt numbers on INSERT:
--    Format: REC-<student_first_name>-<YYYYMMDD>-<seq> in Asia/Kolkata time
-- 3. Prohibit direct modifications to receipt_number on UPDATE
-- 4. Enforce NOT NULL and UNIQUE on public.fees(receipt_number)
-- ============================================================================

-- Step 1: Create receipt_counters table
CREATE TABLE IF NOT EXISTS public.receipt_counters (
  student_id TEXT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  date_key TEXT NOT NULL, -- 'YYYYMMDD'
  last_seq INT NOT NULL DEFAULT 0,
  PRIMARY KEY (student_id, date_key)
);

-- Enable RLS on receipt_counters
ALTER TABLE public.receipt_counters ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rls_receipt_counters_service_role ON public.receipt_counters;
CREATE POLICY rls_receipt_counters_service_role ON public.receipt_counters
  FOR ALL
  TO service_role, postgres
  USING (true)
  WITH CHECK (true);

-- Step 2: Trigger function for receipt generation & immutability
CREATE OR REPLACE FUNCTION public.trg_fees_receipt_number()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_first_name TEXT;
  v_date_key TEXT;
  v_next_seq INT;
  v_clean_name TEXT;
BEGIN
  -- Handle INSERT: Generate immutable system receipt
  IF TG_OP = 'INSERT' THEN
    -- If caller supplied a receipt_number, reject it
    IF NEW.receipt_number IS NOT NULL AND NEW.receipt_number <> '' THEN
      RAISE EXCEPTION 'receipt_number cannot be supplied by clients; it is automatically generated by the system.';
    END IF;

    -- 1. Retrieve student first_name from public.students
    SELECT TRIM(first_name) INTO v_first_name
    FROM public.students
    WHERE id = NEW.student_id;

    -- Fallback to first word of name or 'Student' if missing
    IF v_first_name IS NULL OR v_first_name = '' THEN
      SELECT SPLIT_PART(TRIM(name), ' ', 1) INTO v_first_name
      FROM public.students
      WHERE id = NEW.student_id;
    END IF;

    IF v_first_name IS NULL OR v_first_name = '' THEN
      v_first_name := 'Student';
    END IF;

    -- Clean name: remove non-alphanumeric characters
    v_clean_name := REGEXP_REPLACE(v_first_name, '[^a-zA-Z0-9]', '', 'g');
    IF v_clean_name = '' THEN
      v_clean_name := 'Student';
    END IF;
    v_clean_name := INITCAP(v_clean_name);

    -- 2. Resolve Asia/Kolkata date key: YYYYMMDD
    v_date_key := TO_CHAR(NOW() AT TIME ZONE 'Asia/Kolkata', 'YYYYMMDD');

    -- 3. Atomic sequence generation via receipt_counters upsert
    INSERT INTO public.receipt_counters (student_id, date_key, last_seq)
    VALUES (NEW.student_id, v_date_key, 1)
    ON CONFLICT (student_id, date_key) DO UPDATE
    SET last_seq = receipt_counters.last_seq + 1
    RETURNING last_seq INTO v_next_seq;

    -- 4. Construct formatted receipt number: REC-<Name>-<YYYYMMDD>-<001>
    IF v_next_seq >= 1000 THEN
      NEW.receipt_number := 'REC-' || v_clean_name || '-' || v_date_key || '-' || v_next_seq::TEXT;
    ELSE
      NEW.receipt_number := 'REC-' || v_clean_name || '-' || v_date_key || '-' || LPAD(v_next_seq::TEXT, 3, '0');
    END IF;

    RETURN NEW;
  END IF;

  -- Handle UPDATE: Enforce immutability
  IF TG_OP = 'UPDATE' THEN
    IF NEW.receipt_number IS DISTINCT FROM OLD.receipt_number THEN
      RAISE EXCEPTION 'receipt_number is immutable and cannot be modified once created.';
    END IF;
    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$;

-- Step 3: Attach trigger to public.fees
DROP TRIGGER IF EXISTS trg_fees_receipt_number ON public.fees;
CREATE TRIGGER trg_fees_receipt_number
  BEFORE INSERT OR UPDATE ON public.fees
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_fees_receipt_number();

-- Step 4: Ensure existing row has receipt_number before setting NOT NULL
UPDATE public.fees
SET receipt_number = 'REC-Legacy-' || TO_CHAR(created_at AT TIME ZONE 'Asia/Kolkata', 'YYYYMMDD') || '-001'
WHERE receipt_number IS NULL;

-- Step 5: Enforce NOT NULL and UNIQUE constraint
ALTER TABLE public.fees ALTER COLUMN receipt_number SET NOT NULL;

DROP INDEX IF EXISTS idx_fees_receipt_number_unique;
CREATE UNIQUE INDEX idx_fees_receipt_number_unique ON public.fees(receipt_number);

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
