-- ============================================================================
-- SMART PEN ACADEMY - MIGRATION 010: FIX FEE RECEIPT TRIGGER USER JOIN
-- 010_fix_trg_fees_receipt_number.sql
--
-- Fixes public.trg_fees_receipt_number() to resolve student first_name by
-- joining public.users via public.students(user_id), strictly aligning with
-- the database schema where first_name resides on public.users.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.trg_fees_receipt_number()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_first_name TEXT;
  v_date_key TEXT;
  v_next_seq INT;
  v_clean_name TEXT;
BEGIN
  -- Handle INSERT: Generate immutable system receipt
  IF TG_OP = 'INSERT' THEN
    -- If caller supplied a receipt_number, reject it
    IF NEW.receipt_number IS NOT NULL AND NEW.receipt_number <> '' THEN
      RAISE EXCEPTION 'receipt_number cannot be supplied by clients; it is automatically generated by the system.';
    END IF;

    -- 1. Retrieve student first_name from public.users via public.students
    SELECT TRIM(u.first_name) INTO v_first_name
    FROM public.students s
    LEFT JOIN public.users u ON s.user_id = u.id
    WHERE s.id = NEW.student_id;

    -- Fallback to 'Student' if missing or unlinked
    IF v_first_name IS NULL OR v_first_name = '' THEN
      v_first_name := 'Student';
    END IF;

    -- Clean name: remove non-alphanumeric characters
    v_clean_name := REGEXP_REPLACE(v_first_name, '[^a-zA-Z0-9]', '', 'g');
    IF v_clean_name = '' THEN
      v_clean_name := 'Student';
    END IF;
    v_clean_name := INITCAP(v_clean_name);

    -- 2. Resolve Asia/Kolkata date key: YYYYMMDD
    v_date_key := TO_CHAR(NOW() AT TIME ZONE 'Asia/Kolkata', 'YYYYMMDD');

    -- 3. Atomic sequence generation via receipt_counters upsert
    INSERT INTO public.receipt_counters (student_id, date_key, last_seq)
    VALUES (NEW.student_id, v_date_key, 1)
    ON CONFLICT (student_id, date_key) DO UPDATE
    SET last_seq = receipt_counters.last_seq + 1
    RETURNING last_seq INTO v_next_seq;

    -- 4. Construct formatted receipt number: REC-<Name>-<YYYYMMDD>-<001>
    IF v_next_seq >= 1000 THEN
      NEW.receipt_number := 'REC-' || v_clean_name || '-' || v_date_key || '-' || v_next_seq::TEXT;
    ELSE
      NEW.receipt_number := 'REC-' || v_clean_name || '-' || v_date_key || '-' || LPAD(v_next_seq::TEXT, 3, '0');
    END IF;

    RETURN NEW;
  END IF;

  -- Handle UPDATE: Enforce immutability
  IF TG_OP = 'UPDATE' THEN
    IF NEW.receipt_number IS DISTINCT FROM OLD.receipt_number THEN
      RAISE EXCEPTION 'receipt_number is immutable and cannot be modified once created.';
    END IF;
    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$;

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
